services:
  - type: web
    name: bitget-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: BITGET_API_KEY
        value: "bg_0890dd661ffd67da87e32a8e07c42f0a"
      - key: BITGET_API_SECRET
        value: "08d6f7e390247cb6acc0d2e360abfe1a79ab6ba41fcc44c21ba6293eaa940808"
      - key: BITGET_API_PASSPHRASE
        value: "127642371"
      - key: BITGET_SYMBOLS
        value: "BTCUSDT,ETHUSDT,XRPUSDT"
      - key: BITGET_INTERVAL
        value: "10"
      - key: BITGET_PRODUCT_TYPE
        value: "susdt-futures"
      - key: NEWS_API_KEY
        value: "47578865d3844babaf682e7bdca163a0"
